environment:

  matrix:
  - BUILD_TARGET: windows_msvc
    
  - BUILD_TARGET: unix
    
  - BUILD_TARGET: android
    
matrix:
  fast_finish: false

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\build_windows.sh %BUILD_TARGET%

#after_build:

artifacts:
  - path: src
    name: RabbitImThirdLibrarySource

test: off

deploy:
  provider: FTP 
  protocol: sftp 
  host: frs.sourceforge.net 
  username: kl222,rabbitim-third-library
  #密码用这个加密 https://ci.appveyor.com/tools/encrypt
  password: 
    secure: 2WEtOQrdty3V3g0aEVvS3Q== 
  folder: pfs/project/rabbitim-third-library/release
  draft: false
  active_mode: false 

#deploy:
#  provider: GitHub
#  release: rabbitim-third-library-v$(appveyor_build_version)
#  description: 'rabbitim-third-library-v$(appveyor_build_version)'
#  #token 在这个地址产生 https://github.com/settings/tokens 用这个加密 https://ci.appveyor.com/tools/encrypt
#  auth_token:
#    secure: ZwS9M6Ide+GfM4kLxJ5b9tRoB1wn/56nZRCAIP6Z7s3+YwcE+cx0Dv0d6X82lidF
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    #appveyor_repo_tag: true        # deploy on tag push only
